name: Yi Qu
url: "http://imquyi.com"
author: Yi Qu

google_analytics: UA-5424359-1
duoshuo: imquyi

markdown: kramdown
pygments: true
permalink: /blog/:year/:month/:title/
paginate: 5
paginate_path: "blog/page/:num/"

links:
  - name: Blog
    url: /blog/
  - name: Vitae
    url: /vitae/

social:
  - name: E-mail
    url: "mailto:rangerqu@gmail.com"
  - name: Twitter
    url: "https://twitter.com/rangerqu"
  - name: Weibo
    url: "https://github.com/rangerqu"
